// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTd92rcNbcN2neSdIfmYallHBf_VnYepU',
    appId: '1:736908291694:web:da7002f778dd6490b2007f',
    messagingSenderId: '736908291694',
    projectId: 'intrepid-charge-479905-m8',
    authDomain: 'intrepid-charge-479905-m8.firebaseapp.com',
    storageBucket: 'intrepid-charge-479905-m8.firebasestorage.app',
    measurementId: 'G-ZPYNR24ZKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA2EA8GCf7XDjzlApdljIhGfs82vgn-70',
    appId: '1:736908291694:android:5be13c933d470056b2007f',
    messagingSenderId: '736908291694',
    projectId: 'intrepid-charge-479905-m8',
    storageBucket: 'intrepid-charge-479905-m8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoEDSs6nAgGu7Vq_qljz8hsQzN8-GMmgI',
    appId: '1:736908291694:ios:27b65d7fb1eadc2db2007f',
    messagingSenderId: '736908291694',
    projectId: 'intrepid-charge-479905-m8',
    storageBucket: 'intrepid-charge-479905-m8.firebasestorage.app',
    iosBundleId: 'com.example.fireBaseProject2',
  );
}
